# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
# Custom parameters here if needed

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false   # Services are private by default (good practice)

    # Registers all services in src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Tests/'
            - '../src/Kernel.php'

    # Make controllers public and tag them correctly
    App\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']
